export const LIST_ADMIN_SUCCESS = 'ADMIN/LIST_ADMIN_SUCCESS';
export const ADMIN_DELETE_SUCCESS = 'ADMIN/ADMIN_DELETE_SUCCESS';
export const ADMIN_DETAIL_SUCCESS = 'ADMIN/ADMIN_DETAIL_SUCCESS';
export const ADMIN_UPDATE_SUCCESS = 'ADMIN/ADMIN_UPDATE_SUCCESS';
export const ADMIN_CREATE_SUCCESS = 'ADMIN/ADMIN_CREATE_SUCCESS';
