export const SAVE_LOGGED_USER = 'AUTH/SAVE_LOGGED_USER';
export const REMOVE_LOGGED_USER = 'AUTH/REMOVE_LOGGED_USER';
export const SAVE_CURRENT_ROUTE_STATE = 'AUTH/SAVE_CURRENT_ROUTE_STATE';
export const SAVE_TOKEN = 'AUTH/SAVE_TOKEN';

