export const JOB_BROKER_SUCCESS = 'BROKER/JOB_BROKER_SUCCESS';
export const LIST_BROKER_SUCCESS = 'BROKER/LIST_BROKER_SUCCESS';
export const DETAIL_BROKER_SUCCESS = 'BROKER/DETAIL_BROKER_SUCCESS';
export const POST_BROKER_SUCCESS = 'BROKER/POST_BROKER_SUCCESS';
export const PUT_BROKER_SUCCESS = 'BROKER/PUT_BROKER_SUCCESS';
export const DELETE_BROKER_SUCCESS = 'BROKER/DELETE_BROKER_SUCCESS';
export const LIST_BROKER_PAGINATE_SUCCESS = 'BROKER/LIST_BROKER_PAGINATE_SUCCESS';