export const LIST_JOB_SUCCESS = 'JOB/LIST_JOB_SUCCESS';
export const DETAIL_JOB_SUCCESS = 'JOB/DETAIL_JOB_SUCCESS';
export const DELETE_JOB_SUCCESS = 'JOB/DELETE_JOB_SUCCESS';
export const UPDATE_JOB_SUCCESS = 'JOB/DELETE_JOB_UPDATE';
export const CREATE_JOB_SUCCESS = 'JOB/CREATE_JOB_SUCCESS';
export const SEARCH_JOB_SUCCESS = 'JOB/SEARCH_JOB_SUCCESS';
export const ACTIVE_JOB_SUCCESS = 'JOB/ACTIVE_JOB_SUCCESS';



