export const TOKEN_EXPIRED = 'JWT/TOKEN_EXPIRED';
export const ADD_API_TO_WAITING_BUFFER = 'JWT/ADD_API_TO_WAITING_BUFFER';
export const FINISHED_REQUEST_ALL_WAITING_APIS = 'JWT/FINISHED_REQUEST_ALL_WAITING_APIS';
export const RECALL_ALL_WAITING_APIS = 'JWT/RECALL_ALL_WAITING_APIS';
export const UPDATE_REFRESH_TOKEN = 'JWT/UPDATE_REFRESH_TOKEN';