export const LIST_USER_SUCCESS = 'USERS/LIST_USER_SUCCESS';
export const DETAIL_USER_SUCCESS = 'USERS/DETAIL_USER_SUCCESS';
export const STATISTICS_USER_SUCCESS = 'USERS/STATISTICS_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'USERS/DELETE_USER_SUCCESS';
export const DISABLE_USER_SUCCESS = 'USERS/DISABLE_USER_SUCCESS';